all: q1 q4 q5 q6 q7

clean:
	rm -f q1 q4 q5 q6 q7

q1: q1.c
	gcc -o q1 q1.c -g -Wall

q4: q4.c
	gcc -o q4 q4.c -g -Wall

q5: q5.c
	gcc -o q5 q5.c -g -Wall

q6: q6.c
	gcc -o q6 q6.c -g -Wall

q7: q7.c
	gcc -o q7 q7.c -g -Wall